# Generated by Django 2.1.1 on 2018-10-13 12:47

import dirtyfields.dirtyfields
import django.contrib.postgres.fields.hstore
import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeArea',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('flag_image', models.URLField(blank=True, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ElectoralDistrict',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegislativeHouse',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('administrative_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikidata.AdministrativeArea')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikidata.Country')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegislativeHouseTerm',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('number_of_seats', models.IntegerField(blank=True, null=True)),
                ('number_of_districts', models.IntegerField(blank=True, null=True)),
                ('legislative_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikidata.LegislativeHouse')),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegislativeMembership',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikidata.ElectoralDistrict')),
            ],
            options={
                'ordering': ('start', 'end'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LegislativeTerm',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('start', 'end'),
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ModerationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=64)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('creation', models.BooleanField(default=False)),
                ('deletion', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('facebook_id', models.CharField(blank=True, max_length=100)),
                ('twitter_id', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='person',
            name='sex_or_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikidata.Term'),
        ),
        migrations.AddField(
            model_name='legislativeterm',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikidata.Position'),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='end_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_cause_of_legislative_memberships', to='wikidata.Term'),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='legislative_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikidata.LegislativeHouse'),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='legislative_terms',
            field=models.ManyToManyField(blank=True, to='wikidata.LegislativeTerm'),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikidata.Person'),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikidata.Position'),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='subject_has_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_role_of_legislative_memberships', to='wikidata.Term'),
        ),
        migrations.AddField(
            model_name='legislativehouseterm',
            name='legislative_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikidata.LegislativeTerm'),
        ),
        migrations.AddField(
            model_name='legislativehouseterm',
            name='term_specific_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikidata.Position'),
        ),
        migrations.AddField(
            model_name='legislativehouse',
            name='legislative_terms',
            field=models.ManyToManyField(through='wikidata.LegislativeHouseTerm', to='wikidata.LegislativeTerm'),
        ),
        migrations.AddField(
            model_name='legislativehouse',
            name='positions',
            field=models.ManyToManyField(to='wikidata.Position'),
        ),
        migrations.AlterIndexTogether(
            name='moderationitem',
            index_together={('content_type', 'object_id')},
        ),
    ]
