# Generated by Django 2.1.1 on 2018-10-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legislativemembership',
            name='legislative_term',
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='legislative_terms',
            field=models.ManyToManyField(blank=True, null=True, to='wikidata.LegislativeTerm'),
        ),
    ]
