# Generated by Django 2.1.1 on 2018-10-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0002_auto_20181003_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legislativemembership',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
