# Generated by Django 2.1.1 on 2018-11-07 17:27

import dirtyfields.dirtyfields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0002_legislativeterm_series_ordinal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, models.Model),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='independent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='parliamentary_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parliamentary_group_of_legislative_memberships', to='wikidata.Organization'),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_of_legislative_memberships', to='wikidata.Organization'),
        ),
    ]
