# Generated by Django 2.1.1 on 2018-11-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0003_auto_20181107_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='electoraldistrict',
            name='legislative_house',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='wikidata.LegislativeHouse',
            ),
        ),
    ]
