# Generated by Django 2.1.1 on 2018-10-04 12:16

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0003_auto_20181003_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('id', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('labels', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('identifiers', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_links', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('wikipedia_article_titles', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='legislativemembership',
            options={'ordering': ('start', 'end')},
        ),
        migrations.AlterModelOptions(
            name='legislativeterm',
            options={'ordering': ('start', 'end')},
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='end_cause',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_cause_of_legislative_memberships', to='wikidata.Term'),
        ),
        migrations.AddField(
            model_name='legislativemembership',
            name='subject_has_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_role_of_legislative_memberships', to='wikidata.Term'),
        ),
    ]
