# Generated by Django 2.1.1 on 2018-12-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0004_electoraldistrict_legislative_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='legislativehouse',
            name='number_of_districts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legislativehouse',
            name='number_of_seats',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
