# Generated by Django 2.1.1 on 2018-10-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0004_auto_20181004_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='legislativemembership',
            name='legislative_terms',
            field=models.ManyToManyField(blank=True, to='wikidata.LegislativeTerm'),
        ),
    ]
