# Generated by Django 2.1.1 on 2018-10-04 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0005_auto_20181004_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='person',
            name='sex_or_gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikidata.Term'),
        ),
    ]
