# Generated by Django 2.1.1 on 2018-10-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wikidata', '0006_auto_20181004_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationitem',
            name='object_id',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterIndexTogether(
            name='moderationitem',
            index_together={('content_type', 'object_id')},
        ),
    ]
