# Generated by Django 2.1.5 on 2019-01-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boundaries', '0007_auto_20180325_1421'),
        ('wikidata', '0006_country_iso_3166_1_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativearea',
            name='boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boundaries.Boundary'),
        ),
        migrations.AddField(
            model_name='country',
            name='boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boundaries.Boundary'),
        ),
        migrations.AddField(
            model_name='electoraldistrict',
            name='boundary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='boundaries.Boundary'),
        ),
    ]
