# Generated by Django 2.1.5 on 2019-01-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0007_add_boundary_foreignkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativearea',
            name='geoshape_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='geoshape_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electoraldistrict',
            name='geoshape_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
