# Generated by Django 2.1.1 on 2018-10-05 09:13

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0007_auto_20181005_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationitem',
            name='deletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='moderationitem',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
    ]
