# Generated by Django 2.1.5 on 2019-01-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0008_labels_last_queued'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='refresh_legislatures_last_queued',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legislativehouse',
            name='refresh_districts_last_queued',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legislativehouse',
            name='refresh_members_last_queued',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
