# Generated by Django 2.1.5 on 2019-01-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wikidata', '0009_legislature_last_queued'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativearea',
            name='geoshape_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativearea',
            name='geoshape_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='administrativearea',
            name='refresh_geoshape_last_queued',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='geoshape_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='geoshape_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='refresh_geoshape_last_queued',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electoraldistrict',
            name='geoshape_last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electoraldistrict',
            name='geoshape_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electoraldistrict',
            name='refresh_geoshape_last_queued',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
