SELECT DISTINCT ?adminArea {
  {
    VALUES ?adminArea { wd:{{ country.id }} }
  } UNION {
    # Find regional admin areas of this country (generally FLACSen)
    ?adminArea wdt:P17 wd:{{ country.id }} ;
          wdt:P31/wdt:P279* wd:Q56061 .
  }

  # Remove admin areas that have ended
  FILTER NOT EXISTS { ?adminArea wdt:P582|wdt:P576 ?adminAreaEnd . FILTER (?adminAreaEnd < NOW()) }
}