SELECT ?constituency ?constituencyLabel ?start ?end ?geoshape {
  ?constituencyType wdt:P279* ?constituencySupertype .
  ?constituencySupertype p:P279 ?constituencyTypeSubclassOfStatement .
  ?constituencyTypeSubclassOfStatement ps:P279/wdt:P279* wd:Q192611 ;
                                       pq:P642 wd:{{ house.id }} .
  ?constituency wdt:P31 ?constituencyType .
  OPTIONAL {
    ?constituency wdt:P571 ?start .
  }
  OPTIONAL {
    ?constituency wdt:P576 ?end .
  }
  OPTIONAL { ?constituency wdt:P3896 ?geoshape }       # geoshape
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en" }
}
